### ISSUE TITLE
Run in daemon w/o status icon

### ISSUE THREAD

**Issue by MMR-Burhan** [rickyrockrat/parcellite#2]
How to run parcellite in daemon mode without the status bar icon ?

**Comment by MMR-Burhan** [comment]
Sorry , I referred from http://parcellite.sourceforge.net/?page_id=31 which showed daemon option. But seeing the change-log,  daemon feature is deprecated . So this issue is pointless. Thanks for the tool.

**Comment by rickyrockrat** [comment]
I removed the -d option because I did not see a reason for it. If there is a reason to not display the status icon, I can add another option to run without a systray icon.

-d was from the previous author, and since parcellite usually runs as a daemon, it was a little confusing to me.

So is there a need for not showing the status icon?

**Comment by MMR-Burhan** [comment]
Doesn't "parcellite -n" hide indicator icon ? 
I need a clipboard manager to do just the basic copy-paste with clipboard in my i3-wm that is provided by DE by default. And I don't like an icon constantly being there which I have no use.

**Comment by rickyrockrat** [comment]
It does indeed. I've added all these features users asked for, then forget they are there... :)
