### ISSUE TITLE
Item copied to Clipboard list becomes invisible if already present in persistent history

### ISSUE THREAD

**Issue by rgreen5** [rickyrockrat/parcellite#74]
1. Copy a text string into the clipboard.
2. Open the clipboard manager, right-click on the string and select "Edit".
3. Add a space before the first character, then OK.

EXPECTED RESULT: The space appears in the text string in the clipboard manager list.
ACTUAL RESULT: The entry becomes invisible; if you open the edit window, the space has disappeared again.

4. You may get a similar problem if you copy a text string to the clipboard with a space as the first character.

Linux Mint 20.1 / Cinnamon 4.8.6.

**Comment by rickyrockrat** [comment]
I need your RC. Parcellite has a setting that clears whitespace.

**Comment by rgreen5** [comment]
Yes, I checked the "Behavior" and "clear whitespace" definately wasn't ticked. However, it's working now and I can't reproduce the bug.

**Comment by rgreen5** [comment]
Did a bit more investigation. It seems if you add an entry to the clipboard list and it is already present in the persistent history, it becomes invisible in the former.

**Comment by rickyrockrat** [comment]
By design, you should only have one clipboard entry globally. In other words, if the exact same text is copied and already exists in the persistent history, it automatically gets removed from the regular list. It shouldn't be invisible.

If you want,you can create a feature for this, but you are the first one since I've taken over development in 2010 that wanted this feature.
