### ISSUE TITLE
Monochrome icon for GNOME Shell 

### ISSUE THREAD

**Issue by PanderMusubi** [rickyrockrat/parcellite#8]
Please show a monochrome icon in the icon tray when Parcellite is run in GNOME Shell. The deisng also has to be simplified. I would like to sugget the outline of the current icon and a cut-out of the letter P in the middle. All using only transparant and one very light gray color as GNOME has in its guidelines.

PS See also https://sourceforge.net/p/parcellite/feature-requests/71/ Better close down on of the issue reporting services so all is maintained in one place.

**Comment by rickyrockrat** [comment]
Already Done. Provide your own. Preferences->Display->Parcellite Icon Name. You can use any icon name your system can find. Usually /usr/share/pixmaps

**Comment by jbicha** [comment]
The easy and correct way to fix this is to ship this icon:

`/usr/share/icons/hicolor/symbolic/apps/parcellite-symbolic.svg`

Look in that directory in a recent up-to-date version of GNOME to see what other apps do.

**Comment by PanderMusubi** [comment]
@jbicha, parcellite whould ship that?

**Comment by jbicha** [comment]
@PanderMusubi Sure, if the developer wants this to just work like it does for other apps.

**Comment by PanderMusubi** [comment]
Hope this issue gets reopened

**Comment by rickyrockrat** [comment]
This is more of a theme issue. Only Gnome breaks things as far as I know. Drop that icon down on your system, then set up the option in Parcellite, and you have the icon. Next year, it will be a new Icon, and last year it was something different.  The whole reason the option exists is that other users did not like the stock icon, so I provided something users could change.  I also note that no one has provided an Icon. 

Jbicha, you assume that I have the time and desire to install a 'recent up-to-date version of GNOME', just so I can see said icon. If the icon already exists, then use it. If you set the icon, and it does not work, then provide a bug report stating the exact steps to produce the problem. Since I do not know the licensing behind the icon, I may or may not be able to include it in my source.

**Comment by bungabunga** [comment]
hey, on the new Ubuntu 17.10 that uses Gnome there's no Preferences->Display setting. anybody know the way to change the icon to a custome one?
